name: Strictacode

on:
  push:
    branches:
      - 0.0.x
  pull_request:
    branches:
      - 0.0.x

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - uses: ./.github/actions/analyze
        with:
          install-cmd: pip install strictacode
        env:
          STRICTACODE_SCORE: "40"
          STRICTACODE_RP: "50"
          STRICTACODE_OP: "50"
          STRICTACODE_IMB: "40"
          STRICTACODE_DENSITY: "30"
          STRICTACODE_SCORE_DIFF: "3"
          STRICTACODE_RP_DIFF: "5"
          STRICTACODE_OP_DIFF: "5"
#          STRICTACODE_IMB_DIFF: "5"
          STRICTACODE_DENSITY_DIFF: "3"
